### ISSUE TITLE
General Q

### ISSUE THREAD

**Issue by v1gnesh** [DataEngineeringLabs/arrow2-convert#115]
Hello,

Thank you for sharing your excellent, excellent work.

When you find time, can you please update the `complex_example` with examples showing the latest capabilities?

Any guidane on the GAT refactor and adding support for things like:
```rust
pub struct Numeric<const N: usize>(
    #[deku(map = |num: [u8; N]| LittleEndian::read_int(&num, N))] pub(crate) i64,
);
```

Any guidance on surfacing the `transparent` capability?
https://github.com/DataEngineeringLabs/arrow2-convert/issues/81

Thanks in advance!

**Comment by ncpenke** [comment]
Thank you @v1gnesh. GAT refactor is 90% complete, but I've been busy the last few months so haven't had a chance to finish. Hoping to wrap it up in the upcoming weeks. The refactor touches a lot of the core macro logic, but can either implement transparent or update the ticket with guidance. Thanks!
